import type { Metadata } from "next";
import { Saira } from 'next/font/google'
import "./globals.css";
import Header from "@/components/Header";
import { Provider } from "jotai";



export const saira = Saira({
  subsets: ["latin"], variable: '--font-saira',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={saira.variable}>

      <body >
        <Provider >
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
